version: "3.2"
services:
    web:
      image: php:7.4-apache
      build: .
      ports:
        - 80:80
      volumes:
        - ./advocatus:/var/www/html/
        - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini